// ข้อมูลเมนู Database แบบสมบูรณ์ (46 เมนู แยก Step ชัดเจน)
const menuDatabase = [
    // ลาเต้
    { name: "ลาเต้ 16oz. (หวานปกติ)", steps: [ { instruction: "ความหวาน", correct: "นมข้น 20ml.", wrong: ["นมข้น 10ml."] }, { instruction: "นม", correct: "นมLay 120ml.", wrong: ["นมสด 100ml."] }, { instruction: "เบสกาแฟ", correct: "ใส่กาแฟ", wrong: ["ไม่ต้องใส่กาแฟ","ใส่ชาแทน"] } ] },
    { name: "ลาเต้ 16oz. (หวานน้อย)", steps: [ { instruction: "ความหวาน", correct: "นมข้น 10ml.", wrong: ["นมข้น 20ml."] }, { instruction: "นม", correct: "นมLay 120ml.", wrong: ["นมสด 100ml."] }, { instruction: "เบสกาแฟ", correct: "ใส่กาแฟ", wrong: ["ไม่ต้องใส่กาแฟ","ใส่ชาแทน"] } ] },

    // อเมริกาโน่พีช
    { name: "อเมริกาโน่พีช 16oz. (หวานปกติ)", steps: [ { instruction: "เติมน้ำ", correct: "น้ำ 30ml.", wrong: ["น้ำ 60ml."] }, { instruction: "ปริมาณชาพีช", correct: "ผงชาพีช 3 ช้อน", wrong: ["ผงชาพีช 2 ช้อน"] }, { instruction: "ละลายชา", correct: "น้ำร้อน 3oz.", wrong: ["น้ำร้อน 4oz."] }, { instruction: "เบสกาแฟ", correct: "ใส่กาแฟ", wrong: ["ไม่ต้องใส่กาแฟ","ใส่ชาแทน"] } ] },
    { name: "อเมริกาโน่พีช 16oz. (หวานน้อย)", steps: [ { instruction: "เติมน้ำ", correct: "น้ำ 30ml.", wrong: ["น้ำ 60ml."] }, { instruction: "ปริมาณชาพีช", correct: "ผงชาพีช 2 ช้อน", wrong: ["ผงชาพีช 3 ช้อน"] }, { instruction: "ละลายชา", correct: "น้ำร้อน 3oz.", wrong: ["น้ำร้อน 4oz."] }, { instruction: "เบสกาแฟ", correct: "ใส่กาแฟ", wrong: ["ไม่ต้องใส่กาแฟ","ใส่ชาแทน"] } ] },

    // อเมริกาโน่น้ำผึ้ง
    { name: "อเมริกาโน่น้ำผึ้ง 16oz. (คั่วเข้ม หวานปกติ)", steps: [ { instruction: "ความหวาน", correct: "น้ำผึ้ง 30ml.", wrong: ["น้ำผึ้ง 15ml."] }, { instruction: "เติมน้ำ", correct: "น้ำ 120ml.", wrong: ["น้ำ 100ml."] }, { instruction: "เบสกาแฟ", correct: "ใส่กาแฟ", wrong: ["ไม่ต้องใส่กาแฟ","ใส่ชาแทน"] } ] },
    { name: "อเมริกาโน่น้ำผึ้ง 16oz. (คั่วกลาง หวานน้อย)", steps: [ { instruction: "ความหวาน", correct: "น้ำผึ้ง 15ml.", wrong: ["น้ำผึ้ง 30ml."] }, { instruction: "เติมน้ำ", correct: "น้ำ 100ml.", wrong: ["น้ำ 120ml."] }, { instruction: "เบสกาแฟ", correct: "ใส่กาแฟ", wrong: ["ไม่ต้องใส่กาแฟ","ใส่ชาแทน"] } ] },

    // ชาพีช
    { name: "ชาพีช 16oz. (หวานปกติ)", steps: [ { instruction: "ปริมาณชาพีช", correct: "ผงชาพีช 3 ช้อน", wrong: ["ผงชาพีช 2 ช้อน"] }, { instruction: "ละลายชา", correct: "น้ำร้อน 3oz.", wrong: ["น้ำร้อน 4oz."] }, { instruction: "เติมน้ำ", correct: "น้ำ 60ml.", wrong: ["น้ำ 30ml."] } ] },
    { name: "ชาพีช 16oz. (หวานน้อย)", steps: [ { instruction: "ปริมาณชาพีช", correct: "ผงชาพีช 2 ช้อน", wrong: ["ผงชาพีช 3 ช้อน"] }, { instruction: "ละลายชา", correct: "น้ำร้อน 3oz.", wrong: ["น้ำร้อน 4oz."] }, { instruction: "เติมน้ำ", correct: "น้ำ 60ml.", wrong: ["น้ำ 30ml."] } ] },

    // ชาไทย
    { name: "ชาไทย 16oz. (หวานปกติ)", steps: [ { instruction: "ความหวานหลัก", correct: "นมข้น 30ml.", wrong: ["นมข้น 20ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] }, { instruction: "ความมัน", correct: "ครีมเทียม 1 ช้อน", wrong: ["ไม่ใส่ครีมเทียม"] }, { instruction: "สกัดแรก", correct: "ผงชาตรามือ 3 ช้อน สกัด 1oz.", wrong: ["ผงชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพักชา"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 3oz. รวมเป็น 4oz.", wrong: ["รวมเป็น 5oz."] } ] },
    { name: "ชาไทย 16oz. (หวานน้อย)", steps: [ { instruction: "ความหวานหลัก", correct: "นมข้น 20ml.", wrong: ["นมข้น 10ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] }, { instruction: "ความมัน", correct: "ครีมเทียม 1 ช้อน", wrong: ["ไม่ใส่ครีมเทียม"] }, { instruction: "สกัดแรก", correct: "ผงชาตรามือ 3 ช้อน สกัด 1oz.", wrong: ["ผงชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพักชา"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 3oz. รวมเป็น 4oz.", wrong: ["รวมเป็น 5oz."] } ] },
    { name: "ชาไทย 16oz. (หวาน 25%)", steps: [ { instruction: "ความหวานหลัก", correct: "นมข้น 10ml.", wrong: ["นมข้น 15ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] }, { instruction: "ความมัน", correct: "ครีมเทียม 1 ช้อน", wrong: ["ไม่ใส่ครีมเทียม"] }, { instruction: "สกัดแรก", correct: "ผงชาตรามือ 3 ช้อน สกัด 1oz.", wrong: ["ผงชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพักชา"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 3oz. รวมเป็น 4oz.", wrong: ["รวมเป็น 5oz."] } ] },

    // ชาเขียว
    { name: "ชาเขียว 16oz. (หวานปกติ)", steps: [ { instruction: "ความหวานหลัก", correct: "นมข้น 30ml.", wrong: ["นมข้น 15ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] }, { instruction: "ความหอม", correct: "ผงชาอโลม่า 1 ช้อนเล็ก", wrong: ["ไม่ใส่ผงชาอโลม่า"] }, { instruction: "ความมัน", correct: "ครีมเทียม 1 ช้อน", wrong: ["ไม่ใส่ครีมเทียม"] }, { instruction: "สกัดแรก", correct: "ผงตรามือ 3 ช้อน สกัด 1oz.", wrong: ["ผงชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพักชา"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 3oz. รวมเป็น 4oz.", wrong: ["รวมเป็น 5oz."] } ] },
    { name: "ชาเขียว 16oz. (หวานน้อย)", steps: [ { instruction: "ความหวานหลัก", correct: "นมข้น 15ml.", wrong: ["นมข้น 10ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] }, { instruction: "ความหอม", correct: "ผงชาอโลม่า 1 ช้อนเล็ก", wrong: ["ไม่ใส่ผงชาอโลม่า"] }, { instruction: "ความมัน", correct: "ครีมเทียม 1 ช้อน", wrong: ["ไม่ใส่ครีมเทียม"] }, { instruction: "สกัดแรก", correct: "ผงตรามือ 3 ช้อน สกัด 1oz.", wrong: ["ผงชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพักชา"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 3oz. รวมเป็น 4oz.", wrong: ["รวมเป็น 5oz."] } ] },
    { name: "ชาเขียว 16oz. (หวาน 25%)", steps: [ { instruction: "ความหวานหลัก", correct: "นมข้น 10ml.", wrong: ["นมข้น 15ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] }, { instruction: "ความหอม", correct: "ผงชาอโลม่า 1 ช้อนเล็ก", wrong: ["ไม่ใส่ผงชาอโลม่า"] }, { instruction: "ความมัน", correct: "ครีมเทียม 1 ช้อน", wrong: ["ไม่ใส่ครีมเทียม"] }, { instruction: "สกัดแรก", correct: "ผงตรามือ 3 ช้อน สกัด 1oz.", wrong: ["ผงชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพักชา"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 3oz. รวมเป็น 4oz.", wrong: ["รวมเป็น 5oz."] } ] },

    // นมชมพู
    { name: "นมชมพู 16oz. (หวานปกติ)", steps: [ { instruction: "สีและความหวาน", correct: "น้ำแดง 40ml.", wrong: ["น้ำแดง 20ml."] }, { instruction: "นม", correct: "นมLay 150ml.", wrong: ["นมสด 120ml."] } ] },
    { name: "นมชมพู 16oz. (หวาน 50%)", steps: [ { instruction: "สีและความหวาน", correct: "น้ำแดง 20ml.", wrong: ["น้ำแดง 40ml."] }, { instruction: "นม", correct: "นมLay 150ml.", wrong: ["นมสด 120ml."] } ] },

    // นมสดเย็น
    { name: "นมสดเย็น 16oz. (หวานปกติ)", steps: [ { instruction: "ความหวาน", correct: "นมข้น 30ml.", wrong: ["นมข้น 15ml."] }, { instruction: "นม", correct: "นมLay 150ml.", wrong: ["นมสด 150ml."] } ] },
    { name: "นมสดเย็น 16oz. (หวานน้อย)", steps: [ { instruction: "ความหวาน", correct: "นมข้น 15ml.", wrong: ["นมข้น 10ml."] }, { instruction: "นม", correct: "นมLay 150ml.", wrong: ["นมสด 150ml."] } ] },
    { name: "นมสดเย็น 16oz. (หวาน 25%)", steps: [ { instruction: "ความหวาน", correct: "นมข้น 10ml.", wrong: ["นมข้น 15ml."] }, { instruction: "นม", correct: "นมLay 150ml.", wrong: ["นมสด 150ml."] } ] },

    // ชาเขียวมะนาว
    { name: "ชาเขียวมะนาว 16oz.", steps: [ { instruction: "ความหวาน", correct: "ไซรัป 30ml.", wrong: ["ไซรัป 40ml."] }, { instruction: "ความเปรี้ยว", correct: "ผงมะนาว 1 ช้อนเล็ก (5ml.)", wrong: ["ผงมะนาว 1 ½ ช้อน"] }, { instruction: "สกัดแรก", correct: "ชาเขียว 3 ช้อน สกัด 1oz.", wrong: ["ชาเขียว 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพักชา"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 4oz. รวมเป็น 5oz.", wrong: ["รวมเป็น 4oz."] } ] },

    // เมนูอื่นๆ
    { name: "โกโก้ 16oz.", steps: [ { instruction: "ความหวานเสริม", correct: "ไซรัป 15ml.", wrong: ["ไซรัป 30ml."] }, { instruction: "ความหวานหลัก", correct: "นมข้น 30ml.", wrong: ["นมข้น 15ml."] }, { instruction: "นม", correct: "นมLay 30ml.", wrong: ["นมสด 30ml."] }, { instruction: "ละลาย", correct: "น้ำร้อน 3oz.", wrong: ["น้ำร้อน 2oz."] }, { instruction: "ผงโกโก้", correct: "ผงโกโก้ 3oz.", wrong: ["ผงโกโก้ 2oz."] }, { instruction: "ตกแต่ง", correct: "ราดขอบแก้วซอสโกโก้ 2 รอบ", wrong: ["ไม่ต้องราด"] } ] },
    { name: "คาราเมลมัคคิอาโต 16oz.", steps: [ { instruction: "ความหวาน", correct: "ไซรัปคาราเมล 30ml.", wrong: ["ไซรัปคาราเมล 15ml."] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "เบสกาแฟ", correct: "ใส่กาแฟ", wrong: ["ไม่ต้องใส่กาแฟ","ใส่ชาแทน"] }, { instruction: "ตกแต่ง", correct: "ราดคาราเมลขอบแก้ว 2 รอบ", wrong: ["ไม่ต้องราด"] } ] },
    { name: "อเมริกาโน่น้ำช่อดอกมะพร้าว 16oz.", steps: [ { instruction: "ความหวาน", correct: "ช่อดอกน้ำมะพร้าว 90ml.", wrong: ["ช่อดอกน้ำมะพร้าว 120ml."] }, { instruction: "น้ำ", correct: "น้ำ 30ml.", wrong: ["ไม่ต้องเติมน้ำ"] }, { instruction: "เบสกาแฟ", correct: "ใส่กาแฟ", wrong: ["ไม่ต้องใส่กาแฟ","ใส่ชาแทน"] }, { instruction: "ท็อปปิ้ง", correct: "ใส่เนื้อมะพร้าว 1 ชิ้น", wrong: ["ใส่เนื้อมะพร้าว 2 ชิ้น"] } ] },

    { name: "อเมริกาโน่น้ำผึ้งมะนาว 16oz.", steps: [ { instruction: "น้ำ", correct: "น้ำ 2oz.", wrong: ["น้ำ 4oz."] }, { instruction: "ความหวาน 1", correct: "ไซรัป 15ml.", wrong: ["ไซรัป 30ml."] }, { instruction: "ความหวาน 2", correct: "น้ำผึ้ง 15ml.", wrong: ["น้ำผึ้ง 30ml."] }, { instruction: "ความเปรี้ยว", correct: "ผงมะนาว 5g.", wrong: ["ผงมะนาว 10g."] }, { instruction: "กาแฟ", correct: "ใส่กาแฟ (แยกชั้น)", wrong: ["ไม่ต้องใส่กาแฟ","ใส่ชาแทน"] } ] },
    { name: "อเมริกาโน่ส้ม 16oz.", steps: [ { instruction: "น้ำผลไม้", correct: "น้ำส้ม 1 ขวด (แยกชั้น)", wrong: ["น้ำส้ม 90ml."] }, { instruction: "เบสกาแฟ", correct: "ใส่กาแฟ", wrong: ["ไม่ต้องใส่กาแฟ","ใส่ชาแทน"] } ] },

    { name: "ชามะนาว 16oz.", steps: [ { instruction: "ความหวาน", correct: "ไซรัป 30ml.", wrong: ["น้ำผึ้ง 30ml."] }, { instruction: "ความเปรี้ยว", correct: "ผงมะนาว 1 ½ ช้อนเล็ก", wrong: ["ผงมะนาว 1 ช้อน"] }, { instruction: "สกัดแรก", correct: "ผงชาตรามือผสมมังกร 3 ช้อน สกัด 1oz.", wrong: ["ผงชาตรามือ 3 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพัก"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 4oz. รวมเป็น 5oz.", wrong: ["รวมเป็น 4oz."] } ] },


    { name: "ชาเขียวน้ำผึ้งมะนาว 16oz.", steps: [ { instruction: "ความหวาน 1", correct: "ไซรัป 15ml.", wrong: ["ไซรัป 30ml."] }, { instruction: "ความหวาน 2", correct: "น้ำผึ้ง 15ml.", wrong: ["น้ำผึ้ง 30ml."] }, { instruction: "ความเปรี้ยว", correct: "ผงมะนาว 1 ½ ช้อนเล็ก", wrong: ["ผงมะนาว 5ml."] }, { instruction: "สกัดแรก", correct: "ผงชาตรามือ 3 ช้อน สกัด 1oz.", wrong: ["ชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพัก"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 4oz. รวมเป็น 5oz.", wrong: ["รวมเป็น 4oz."] } ] },

    { name: "ชากุหลาบ 16oz.", steps: [ { instruction: "ความหวานหลัก", correct: "นมข้น 30ml.", wrong: ["นมข้น 15ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] }, { instruction: "ความมัน", correct: "ครีมเทียม 1 ช้อน", wrong: ["ไม่ใส่ครีมเทียม"] }, { instruction: "สกัดแรก", correct: "ผงชากุหลาบ 3 ช้อน สกัด 1oz.", wrong: ["ชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพัก"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 3oz. รวมเป็น 4oz.", wrong: ["รวมเป็น 5oz."] } ] },

    { name: "เมนูโซดา 16oz. (เช่น บลูฮาวาย)", steps: [ { instruction: "ไซรัป", correct: "ไซรัปผลไม้ 40ml.", wrong: ["ไซรัปผลไม้ 30ml."] }, { instruction: "โซดาแรก", correct: "ใส่โซดา 30ml. คนให้เข้ากัน", wrong: ["ใส่โซดาทีเดียวเต็ม"] }, { instruction: "ความเปรี้ยว", correct: "เฉพาะบลูฮาวายใส่ผงมะนาว 1/2 ช้อน", wrong: ["ใส่ 1 ช้อน"] }, { instruction: "น้ำแข็ง", correct: "ใส่น้ำแข็ง", wrong: ["ใส่น้ำ"] }, { instruction: "โซดาสุดท้าย", correct: "ใส่โซดาให้เต็ม", wrong: ["ใส่น้ำให้เต็ม"] } ] },

    { name: "นมสดคาราเมล 16oz.", steps: [ { instruction: "นม", correct: "นมสด 150ml.", wrong: ["นมLay 150ml."] }, { instruction: "ความหวาน", correct: "ไซรัปคาราเมล 30ml.", wrong: ["ไซรัป 15ml."] }, { instruction: "ตกแต่ง", correct: "ราดคาราเมลขอบแก้ว 2 รอบ", wrong: ["ไม่ต้องราด"] } ] },

    { name: "เพียวมัทฉะ (เขียนมือ)", steps: [ { instruction: "มัทฉะ", correct: "ผงมัทฉะ 3g.", wrong: ["ผงมัทฉะ 5g."] }, { instruction: "ละลาย", correct: "น้ำร้อน 2oz.", wrong: ["น้ำร้อน 3oz."] }, { instruction: "น้ำ", correct: "เติมน้ำในแก้ว 100ml.", wrong: ["น้ำ 150ml."] }, { instruction: "ขั้นตอนสุดท้าย", correct: "เอามัทฉะราดข้างบน", wrong: ["คนให้เข้ากัน"] } ] },

    { name: "ลิ้นจี่น้ำแดง 16oz.", steps: [ { instruction: "ลิ้นจี่", correct: "ไซรัปลิ้นจี่ 1 ขวด", wrong: ["ไซรัปลิ้นจี่ 30ml."] }, { instruction: "น้ำแดง", correct: "น้ำแดง 20ml.", wrong: ["น้ำแดง 40ml."] } ] },
    { name: "ชาพีช + น้ำผึ้ง 16oz.", steps: [ { instruction: "ความหวาน", correct: "น้ำผึ้ง 30ml.", wrong: ["น้ำผึ้ง 15ml."] }, { instruction: "ชาพีช", correct: "ชาพีช 2 ช้อน", wrong: ["ชาพีช 3 ช้อน"] }, { instruction: "ละลาย", correct: "น้ำร้อน 3oz.", wrong: ["น้ำร้อน 4oz."] }, { instruction: "น้ำ", correct: "น้ำ 60ml.", wrong: ["น้ำ 30ml."] } ] },

    // โคลด์โฟม
    { name: "โคลด์โฟมมัทฉะช่อน้ำดอกมะพร้าว", steps: [ { instruction: "เบส", correct: "ช่อดอกน้ำมะพร้าว 90ml.", wrong: ["ช่อดอก 120ml."] }, { instruction: "น้ำ", correct: "น้ำ 30ml.", wrong: ["ไม่ต้องเติมน้ำ"] }, { instruction: "โฟม: ส่วนของนม", correct: "นมสด 60ml.", wrong: ["นมสด 90ml."] }, { instruction: "โฟม: วิปครีม", correct: "วิป 30ml.", wrong: ["ไม่ใส่วิป"] }, { instruction: "โฟม: ส่วนของชา", correct: "ผงมัทฉะ 5-6g. (ตีจนฟองหนืด)", wrong: ["มัทฉะ 3g."] }, { instruction: "ท็อปปิ้ง", correct: "ใส่เนื้อมะพร้าว 2 ชิ้น", wrong: ["ใส่ 1 ชิ้น"] } ] },
    { name: "โคลด์โฟม ชาเขียวช่อน้ำดอกมะพร้าว", steps: [ { instruction: "โฟม: ส่วนของนม", correct: "นมสด 60ml.", wrong: ["นมสด 90ml."] }, { instruction: "โฟม: วิปครีม", correct: "วิป 30ml.", wrong: ["ไม่ใส่วิป"] }, { instruction: "โฟม: ส่วนของชา", correct: "ชาเขียว 1oz.(30ml.)", wrong: ["ผงชาเขียว 5g."] }, { instruction: "เบส", correct: "ช่อดอกน้ำมะพร้าว 90ml.", wrong: ["ช่อดอก 120ml."] }, { instruction: "น้ำ", correct: "น้ำ 30ml.", wrong: ["ไม่ต้องเติมน้ำ"] } ] },
    { name: "โคลด์โฟมกาแฟลาเต้ช่อน้ำดอกมะพร้าว", steps: [ { instruction: "เบส", correct: "ช่อดอกน้ำมะพร้าว 90ml.", wrong: ["ช่อดอก 120ml."] }, { instruction: "น้ำ", correct: "น้ำ 30ml.", wrong: ["ไม่ต้องเติมน้ำ"] }, { instruction: "โฟม: ส่วนของนม", correct: "นมสด 60ml.", wrong: ["นมสด 90ml."] }, { instruction: "โฟม: วิปครีม", correct: "วิป 30ml.", wrong: ["ไม่ใส่วิป"] }, { instruction: "โฟม: กาแฟ", correct: "ใส่กาแฟ (ตีจนฟองหนืด)", wrong: ["ไม่ต้องใส่กาแฟ","ใส่ชาแทน"] } ] },
    { name: "โคลด์โฟม ชาไทยช่อน้ำดอกมะพร้าว", steps: [ { instruction: "โฟม: ส่วนของนม", correct: "นมสด 60ml.", wrong: ["นมสด 90ml."] }, { instruction: "โฟม: วิปครีม", correct: "วิป 30ml.", wrong: ["ไม่ใส่วิป"] }, { instruction: "โฟม: ส่วนของชา", correct: "ชาไทย 1oz.(30ml.)", wrong: ["ผงชา 5g."] }, { instruction: "เบส", correct: "ช่อดอกน้ำมะพร้าว 90ml.", wrong: ["ช่อดอก 120ml."] }, { instruction: "น้ำ", correct: "น้ำ 30ml.", wrong: ["ไม่ต้องเติมน้ำ"] } ] },
    { name: "โคลด์โฟม โกโก้ช่อน้ำดอกมะพร้าว", steps: [ { instruction: "เบส", correct: "ช่อดอกน้ำมะพร้าว 90ml.", wrong: ["ช่อดอก 120ml."] }, { instruction: "น้ำ", correct: "น้ำ 30ml.", wrong: ["ไม่ต้องเติมน้ำ"] }, { instruction: "โฟม: ส่วนของนม", correct: "นมสด 60ml.", wrong: ["นมสด 90ml."] }, { instruction: "โฟม: วิปครีม", correct: "วิป 30ml.", wrong: ["ไม่ใส่วิป"] }, { instruction: "โฟม: โกโก้", correct: "โกโก้ 1 ช้อน (ตีจนฟองหนืด)", wrong: ["น้ำโกโก้ 30ml."] } ] },

    // มัทฉะแบบต่างๆ
    { name: "ชาใสกุหลาบ 16oz.", steps: [ { instruction: "สกัดแรก", correct: "ผงชากุหลาบ สกัด 1oz.", wrong: ["ผงชากุหลาบ 2 ช้อน"] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพัก"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 4oz. รวมเป็น 5oz.", wrong: ["รวมเป็น 4oz."] }, { instruction: "ความหวาน", correct: "ไซรัป 30ml.", wrong: ["ไซรัป 15ml."] } ] },
    { name: "เพียวมัทฉะ (สูตรพิมพ์)", steps: [ { instruction: "น้ำ", correct: "น้ำ 150ml.", wrong: ["น้ำร้อน 150ml."] }, { instruction: "มัทฉะ", correct: "มัทฉะ 1 ช้อน", wrong: ["มัทฉะ 3g."] }, { instruction: "ขั้นตอน", correct: "ตีให้เข้ากัน", wrong: ["ราดข้างบน"] } ] },
    { name: "มัทฉะลาเต้ 16oz.", steps: [ { instruction: "ความหวานหลัก", correct: "นมข้น 30ml.", wrong: ["นมข้น 15ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "มัทฉะ", correct: "ผงมัทฉะ 1 ช้อน", wrong: ["ผงมัทฉะ 3g."] }, { instruction: "ละลายชา", correct: "น้ำร้อน 2oz.", wrong: ["น้ำร้อน 3oz."] } ] },
    { name: "มัทฉะน้ำช่อดอกมะพร้าว (แยกชั้น)", steps: [ { instruction: "เบส", correct: "ช่อดอกน้ำมะพร้าว 90ml.", wrong: ["ช่อดอก 120ml."] }, { instruction: "น้ำ", correct: "น้ำ 30ml.", wrong: ["ไม่ต้องเติมน้ำ"] }, { instruction: "มัทฉะ", correct: "ผงมัทฉะ 1 ช้อน", wrong: ["ผงมัทฉะ 3g."] }, { instruction: "ละลายชา", correct: "น้ำร้อน 2oz.", wrong: ["น้ำร้อน 3oz."] }, { instruction: "ท็อปปิ้ง", correct: "ใส่เนื้อมะพร้าว 2 ชิ้น", wrong: ["ใส่ 1 ชิ้น"] } ] },
    { name: "มัทฉะน้ำส้ม (แยกชั้น)", steps: [ { instruction: "น้ำผลไม้", correct: "น้ำส้ม 1 ขวด 120ml.", wrong: ["น้ำส้ม 90ml."] }, { instruction: "มัทฉะ", correct: "ผงมัทฉะ 1 ช้อน", wrong: ["ผงมัทฉะ 3g."] }, { instruction: "ละลายชา", correct: "น้ำร้อน 2oz.", wrong: ["น้ำร้อน 3oz."] } ] },
    { name: "มัทฉะมะนาว (แยกชั้น)", steps: [ { instruction: "ความหวาน", correct: "ไซรัป 30ml.", wrong: ["ไซรัป 15ml."] }, { instruction: "ความเปรี้ยว", correct: "ผงมะนาว 1 ½ ช้อน", wrong: ["ผงมะนาว 1 ช้อน"] }, { instruction: "ละลายน้ำ", correct: "ใส่น้ำร้อนให้ถึง 4oz.", wrong: ["ใส่น้ำร้อน 5oz."] }, { instruction: "มัทฉะ", correct: "ผงมัทฉะ 1 ช้อน", wrong: ["ผงมัทฉะ 3g."] }, { instruction: "ละลายชา", correct: "น้ำร้อน 2oz.", wrong: ["น้ำร้อน 3oz."] } ] },
    { name: "มัทฉะน้ำผึ้งมะนาว (แยกชั้น)", steps: [ { instruction: "ความหวาน 1", correct: "น้ำผึ้ง 15ml.", wrong: ["น้ำผึ้ง 30ml."] }, { instruction: "ความหวาน 2", correct: "ไซรัป 15ml.", wrong: ["ไซรัป 30ml."] }, { instruction: "ความเปรี้ยว", correct: "ผงมะนาว 1 ½ ช้อน", wrong: ["ผงมะนาว 1 ช้อน"] }, { instruction: "ละลายน้ำ", correct: "ใส่น้ำร้อนให้ถึง 4oz.", wrong: ["ใส่น้ำร้อน 5oz."] }, { instruction: "มัทฉะ", correct: "ผงมัทฉะ 1 ช้อน", wrong: ["ผงมัทฉะ 3g."] }, { instruction: "ละลายชา", correct: "น้ำร้อน 2oz.", wrong: ["น้ำร้อน 3oz."] } ] },

    // เพิ่มเมนูใหม่
    { name: "โกโก้มิ้นท์ (แยกชั้น) (หวานปกติ)", steps: [ { instruction: "ความหวาน", correct: "ไซรัปมิ้นท์ 30ml.", wrong: ["ไซรัปมิ้นท์ 15ml."] }, { instruction: "นม", correct: "นมสด 100ml.", wrong: ["นมLay 120ml."] }, { instruction: "โกโก้", correct: "โกโก้ 2 ช้อน / น้ำ 2 ออนซ์", wrong: ["โกโก้ 3 ช้อน / น้ำ 2 ออนซ์"] }, { instruction: "ตกแต่ง", correct: "วาดขอบแก้วด้วยโกโก้", wrong: ["ไม่ต้องวาดขอบแก้ว"] } ] },
    { name: "โกโก้มิ้นท์ (แยกชั้น) (หวานน้อย)", steps: [ { instruction: "ความหวาน", correct: "ไซรัปมิ้นท์ 15ml.", wrong: ["ไซรัปมิ้นท์ 30ml."] }, { instruction: "นม", correct: "นมสด 100ml.", wrong: ["นมLay 120ml."] }, { instruction: "โกโก้", correct: "โกโก้ 2 ช้อน / น้ำ 2 ออนซ์", wrong: ["โกโก้ 3 ช้อน / น้ำ 2 ออนซ์"] }, { instruction: "ตกแต่ง", correct: "วาดขอบแก้วด้วยโกโก้", wrong: ["ไม่ต้องวาดขอบแก้ว"] } ] },
    { name: "โกโก้มิ้นท์ (แยกชั้น) (ไม่หวาน)", steps: [ { instruction: "ความหวาน", correct: "ไม่ใส่ไซรัปมิ้นท์ (0ml.)", wrong: ["ไซรัปมิ้นท์ 15ml."] }, { instruction: "นม", correct: "นมสด 100ml.", wrong: ["นมLay 120ml."] }, { instruction: "โกโก้", correct: "โกโก้ 2 ช้อน / น้ำ 2 ออนซ์", wrong: ["โกโก้ 3 ช้อน / น้ำ 2 ออนซ์"] }, { instruction: "ตกแต่ง", correct: "วาดขอบแก้วด้วยโกโก้", wrong: ["ไม่ต้องวาดขอบแก้ว"] } ] },

    { name: "นมชมพู (อัพเดต)", steps: [ { instruction: "ความหวาน", correct: "เฮบลูบอย 30ml.", wrong: ["เฮบลูบอย 40ml."] }, { instruction: "นม", correct: "นม 150ml.", wrong: ["นม 120ml."] } ] },

    { name: "นมสดเย็น (หวานปกติ) (อัพเดต)", steps: [ { instruction: "ความหวาน", correct: "นมข้น 30ml.", wrong: ["นมข้น 15ml."] }, { instruction: "นม", correct: "นม 150ml.", wrong: ["นม 120ml."] } ] },
    { name: "นมสดเย็น (หวานน้อย) (อัพเดต)", steps: [ { instruction: "ความหวาน", correct: "นมข้น 15ml.", wrong: ["นมข้น 30ml."] }, { instruction: "นม", correct: "นม 150ml.", wrong: ["นม 120ml."] } ] },
    { name: "นมสดเย็น (ไม่หวาน) (อัพเดต)", steps: [ { instruction: "ความหวาน", correct: "ไม่ใส่นมข้น (0ml.)", wrong: ["นมข้น 15ml."] }, { instruction: "นม", correct: "นม 150ml.", wrong: ["นม 120ml."] } ] },

    { name: "โคโฟมลาเต้ (แยกชั้น)", steps: [ { instruction: "นม", correct: "นม 60ml.", wrong: ["นม 90ml."] }, { instruction: "วิป", correct: "วิป 30ml.", wrong: ["วิป 40ml."] } ] },

    { name: "มัทฉะลาเต้สตอเบอรี่ (แยกชั้น) (หวานปกติ)", steps: [ { instruction: "สตอเบอรี่", correct: "สตอเบอรี่ 40ml.", wrong: ["สตอเบอรี่ 30ml."] }, { instruction: "นมข้น", correct: "นมข้น 30ml.", wrong: ["นมข้น 15ml."] }, { instruction: "ไซรัป", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "ผงมัทฉะ", correct: "ผงมัทฉะ 1 ช้อน / น้ำ 2 ออนซ์", wrong: ["ผงมัทฉะ 2 ช้อน / น้ำ 2 ออนซ์"] } ] },
    { name: "มัทฉะลาเต้สตอเบอรี่ (แยกชั้น) (หวานน้อย)", steps: [ { instruction: "สตอเบอรี่", correct: "สตอเบอรี่ 40ml.", wrong: ["สตอเบอรี่ 30ml."] }, { instruction: "นมข้น", correct: "นมข้น 15ml.", wrong: ["นมข้น 30ml."] }, { instruction: "ไซรัป", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "ผงมัทฉะ", correct: "ผงมัทฉะ 1 ช้อน / น้ำ 2 ออนซ์", wrong: ["ผงมัทฉะ 2 ช้อน / น้ำ 2 ออนซ์"] } ] },
    { name: "มัทฉะลาเต้สตอเบอรี่ (แยกชั้น) (ไม่หวาน)", steps: [ { instruction: "สตอเบอรี่", correct: "สตอเบอรี่ 40ml.", wrong: ["สตอเบอรี่ 30ml."] }, { instruction: "นมข้น", correct: "ไม่ใส่นมข้น (0ml.)", wrong: ["นมข้น 15ml."] }, { instruction: "ไซรัป", correct: "ไม่ใส่ไซรัป.", wrong: ["ไซรัป 5ml."] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "ผงมัทฉะ", correct: "ผงมัทฉะ 1 ช้อน / น้ำ 2 ออนซ์", wrong: ["ผงมัทฉะ 2 ช้อน / น้ำ 2 ออนซ์"] } ] },

    { name: "ซอฟชาเขียว (แยกชั้น) (หวานปกติ)", steps: [ { instruction: "ความหวาน", correct: "นมข้น 30ml.", wrong: ["นมข้น 15ml."] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "น้ำแข็ง", correct: "ใส่น้ำแข็งครึ่งแก้ว", wrong: ["ใส่น้ำแข็งเต็มแก้ว"] }, { instruction: "ผงชา", correct: "ผงชาเขียว 3 ช้อน / น้ำ 2 ออนซ์", wrong: ["ผงชาเขียว 2 ช้อน / น้ำ 2 ออนซ์"] }, { instruction: "ตกแต่ง", correct: "ใส่ซอฟ + ราดชา + ปั้นโฟม + โรยผง", wrong: ["ใส่ซอฟ + ราดชา"] } ] },
    { name: "ซอฟชาเขียว (แยกชั้น) (หวานน้อย)", steps: [ { instruction: "ความหวาน", correct: "นมข้น 15ml.", wrong: ["นมข้น 30ml."] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "น้ำแข็ง", correct: "ใส่น้ำแข็งครึ่งแก้ว", wrong: ["ใส่น้ำแข็งเต็มแก้ว"] }, { instruction: "ผงชา", correct: "ผงชาเขียว 3 ช้อน / น้ำ 2 ออนซ์", wrong: ["ผงชาเขียว 2 ช้อน / น้ำ 2 ออนซ์"] }, { instruction: "ตกแต่ง", correct: "ใส่ซอฟ + ราดชา + ปั้นโฟม + โรยผง", wrong: ["ใส่ซอฟ + ราดชา"] } ] },
    { name: "ซอฟชาเขียว (แยกชั้น) (ไม่หวาน)", steps: [ { instruction: "ความหวาน", correct: "ไม่ใส่นมข้น (0ml.)", wrong: ["นมข้น 15ml."] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "น้ำแข็ง", correct: "ใส่น้ำแข็งครึ่งแก้ว", wrong: ["ใส่น้ำแข็งเต็มแก้ว"] }, { instruction: "ผงชา", correct: "ผงชาเขียว 3 ช้อน / น้ำ 2 ออนซ์", wrong: ["ผงชาเขียว 2 ช้อน / น้ำ 2 ออนซ์"] }, { instruction: "ตกแต่ง", correct: "ใส่ซอฟ + ราดชา + ปั้นโฟม + โรยผง", wrong: ["ใส่ซอฟ + ราดชา"] } ] },

    { name: "ซอฟชาไทย (แยกชั้น) (หวานปกติ)", steps: [ { instruction: "ความหวาน", correct: "นมข้น 30ml.", wrong: ["นมข้น 15ml."] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "น้ำแข็ง", correct: "ใส่น้ำแข็งครึ่งแก้ว", wrong: ["ใส่น้ำแข็งเต็มแก้ว"] }, { instruction: "ผงชา", correct: "ผงชาไทย 3 ช้อน / น้ำ 2 ออนซ์", wrong: ["ผงชาไทย 2 ช้อน / น้ำ 2 ออนซ์"] }, { instruction: "ตกแต่ง", correct: "ใส่ซอฟ + ราดชา + ปั้นโฟม + โรยผง", wrong: ["ใส่ซอฟ + ราดชา"] } ] },
    { name: "ซอฟชาไทย (แยกชั้น) (หวานน้อย)", steps: [ { instruction: "ความหวาน", correct: "นมข้น 15ml.", wrong: ["นมข้น 30ml."] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "น้ำแข็ง", correct: "ใส่น้ำแข็งครึ่งแก้ว", wrong: ["ใส่น้ำแข็งเต็มแก้ว"] }, { instruction: "ผงชา", correct: "ผงชาไทย 3 ช้อน / น้ำ 2 ออนซ์", wrong: ["ผงชาไทย 2 ช้อน / น้ำ 2 ออนซ์"] }, { instruction: "ตกแต่ง", correct: "ใส่ซอฟ + ราดชา + ปั้นโฟม + โรยผง", wrong: ["ใส่ซอฟ + ราดชา"] } ] },
    { name: "ซอฟชาไทย (แยกชั้น) (ไม่หวาน)", steps: [ { instruction: "ความหวาน", correct: "ไม่ใส่นมข้น (0ml.)", wrong: ["นมข้น 15ml."] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "น้ำแข็ง", correct: "ใส่น้ำแข็งครึ่งแก้ว", wrong: ["ใส่น้ำแข็งเต็มแก้ว"] }, { instruction: "ผงชา", correct: "ผงชาไทย 3 ช้อน / น้ำ 2 ออนซ์", wrong: ["ผงชาไทย 2 ช้อน / น้ำ 2 ออนซ์"] }, { instruction: "ตกแต่ง", correct: "ใส่ซอฟ + ราดชา + ปั้นโฟม + โรยผง", wrong: ["ใส่ซอฟ + ราดชา"] } ] },

    { name: "ซอฟโกโก้ (แยกชั้น) (หวานปกติ)", steps: [ { instruction: "ความหวาน", correct: "นมข้น 30ml.", wrong: ["นมข้น 15ml."] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "น้ำแข็ง", correct: "ใส่น้ำแข็งครึ่งแก้ว", wrong: ["ใส่น้ำแข็งเต็มแก้ว"] }, { instruction: "ผงโกโก้", correct: "ผงโกโก้ 3 ช้อน / น้ำ 2 ออนซ์", wrong: ["ผงโกโก้ 2 ช้อน / น้ำ 2 ออนซ์"] }, { instruction: "ตกแต่ง", correct: "ใส่ซอฟ + ราดโกโก้ + ปั้นโฟม + โรยผง", wrong: ["ใส่ซอฟ + ราดโกโก้"] } ] },
    { name: "ซอฟโกโก้ (แยกชั้น) (หวานน้อย)", steps: [ { instruction: "ความหวาน", correct: "นมข้น 15ml.", wrong: ["นมข้น 30ml."] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "น้ำแข็ง", correct: "ใส่น้ำแข็งครึ่งแก้ว", wrong: ["ใส่น้ำแข็งเต็มแก้ว"] }, { instruction: "ผงโกโก้", correct: "ผงโกโก้ 3 ช้อน / น้ำ 2 ออนซ์", wrong: ["ผงโกโก้ 2 ช้อน / น้ำ 2 ออนซ์"] }, { instruction: "ตกแต่ง", correct: "ใส่ซอฟ + ราดโกโก้ + ปั้นโฟม + โรยผง", wrong: ["ใส่ซอฟ + ราดโกโก้"] } ] },
    { name: "ซอฟโกโก้ (แยกชั้น) (ไม่หวาน)", steps: [ { instruction: "ความหวาน", correct: "ไม่ใส่นมข้น (0ml.)", wrong: ["นมข้น 15ml."] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "น้ำแข็ง", correct: "ใส่น้ำแข็งครึ่งแก้ว", wrong: ["ใส่น้ำแข็งเต็มแก้ว"] }, { instruction: "ผงโกโก้", correct: "ผงโกโก้ 3 ช้อน / น้ำ 2 ออนซ์", wrong: ["ผงโกโก้ 2 ช้อน / น้ำ 2 ออนซ์"] }, { instruction: "ตกแต่ง", correct: "ใส่ซอฟ + ราดโกโก้ + ปั้นโฟม + โรยผง", wrong: ["ใส่ซอฟ + ราดโกโก้"] } ] },

    { name: "ท๊อปฟี้ คอฟฟี้ (แยกชั้น)", steps: [ { instruction: "ความหวาน", correct: "ไซรัปคาราเมล 10ml.", wrong: ["ไซรัปคาราเมล 20ml."] }, { instruction: "นม", correct: "นม 120ml.", wrong: ["นม 100ml."] }, { instruction: "ตกแต่งขอบแก้ว", correct: "วาดขอบด้วยคาราเมล", wrong: ["วาดขอบด้วยโกโก้"] }, { instruction: "กาแฟ", correct: "ใส่กาแฟ (แยกชั้น)", wrong: ["ไม่ต้องใส่กาแฟ", "ใส่ชาแทน"] }, { instruction: "ท็อปปิ้ง", correct: "ใส่คาราเมลก้อน", wrong: ["ไม่ใส่คาราเมลก้อน"] } ] },

    { name: "อเมริกาโน่แอปเปิ้ล (แยกชั้น)", steps: [ { instruction: "น้ำผลไม้", correct: "น้ำแอปเปิ้ล 120ml.", wrong: ["น้ำแอปเปิ้ล 90ml."] }, { instruction: "กาแฟ", correct: "ใส่กาแฟ (แยกชั้น)", wrong: ["ไม่ต้องใส่กาแฟ", "ใส่ชาแทน"] } ] }
];
