        // ข้อมูลเมนู Database แบบสมบูรณ์ (46 เมนู แยก Step ชัดเจน)
        const menuDatabase = [
            // ลาเต้
            { name: "ลาเต้ 16oz. (หวานปกติ)", steps: [ { instruction: "เบสกาแฟ", correct: "กาแฟ 50ml.", wrong: ["กาแฟ 2oz. (60ml.)"] }, { instruction: "นม", correct: "นมLay 120ml.", wrong: ["นมสด 100ml."] }, { instruction: "ความหวาน", correct: "นมข้น หวานปกติ 20ml.", wrong: ["นมข้น 10ml."] } ] },
            { name: "ลาเต้ 16oz. (หวานน้อย)", steps: [ { instruction: "เบสกาแฟ", correct: "กาแฟ 50ml.", wrong: ["กาแฟ 2oz. (60ml.)"] }, { instruction: "นม", correct: "นมLay 120ml.", wrong: ["นมสด 100ml."] }, { instruction: "ความหวาน", correct: "นมข้น หวานน้อย 10ml.", wrong: ["นมข้น 20ml."] } ] },

            // อเมริกาโน่พีช
            { name: "อเมริกาโน่พีช 16oz. (หวานปกติ)", steps: [ { instruction: "เบสกาแฟ", correct: "กาแฟ 2oz.", wrong: ["กาแฟ 50ml."] }, { instruction: "ปริมาณชาพีช", correct: "หวานปกติ ผงชาพีช 3 ช้อน", wrong: ["ผงชาพีช 2 ช้อน"] }, { instruction: "ละลายชา", correct: "น้ำร้อน 3oz.", wrong: ["น้ำร้อน 4oz."] }, { instruction: "เติมน้ำ", correct: "น้ำเปล่า 30 ml.", wrong: ["น้ำเปล่า 60 ml."] } ] },
            { name: "อเมริกาโน่พีช 16oz. (หวานน้อย)", steps: [ { instruction: "เบสกาแฟ", correct: "กาแฟ 2oz.", wrong: ["กาแฟ 50ml."] }, { instruction: "ปริมาณชาพีช", correct: "หวานน้อย ผงชาพีช 2 ช้อน", wrong: ["ผงชาพีช 3 ช้อน"] }, { instruction: "ละลายชา", correct: "น้ำร้อน 3oz.", wrong: ["น้ำร้อน 4oz."] }, { instruction: "เติมน้ำ", correct: "น้ำเปล่า 30 ml.", wrong: ["น้ำเปล่า 60 ml."] } ] },

            // อเมริกาโน่น้ำผึ้ง
            { name: "อเมริกาโน่น้ำผึ้ง 16oz. (คั่วเข้ม หวานปกติ)", steps: [ { instruction: "เบสกาแฟ", correct: "คั่วเข้ม 50ml.", wrong: ["คั่วกลาง 50ml."] }, { instruction: "เติมน้ำ", correct: "น้ำ 120ml.", wrong: ["น้ำ 100ml."] }, { instruction: "ความหวาน", correct: "น้ำผึ้ง หวานปกติ 30ml.", wrong: ["น้ำผึ้ง 15ml."] } ] },
            { name: "อเมริกาโน่น้ำผึ้ง 16oz. (คั่วกลาง หวานน้อย)", steps: [ { instruction: "เบสกาแฟ", correct: "คั่วกลาง 50ml.", wrong: ["คั่วเข้ม 50ml."] }, { instruction: "เติมน้ำ", correct: "น้ำ 100ml.", wrong: ["น้ำ 120ml."] }, { instruction: "ความหวาน", correct: "น้ำผึ้ง หวานน้อย 15ml.", wrong: ["น้ำผึ้ง 30ml."] } ] },

            // ชาพีช
            { name: "ชาพีช 16oz. (หวานปกติ)", steps: [ { instruction: "ละลายชา", correct: "น้ำร้อน 3 oz.", wrong: ["น้ำร้อน 4 oz."] }, { instruction: "ปริมาณชาพีช", correct: "หวานปกติ ผงชาพีช 3 ช้อน", wrong: ["ผงชาพีช 2 ช้อน"] }, { instruction: "เติมน้ำ", correct: "น้ำเปล่า 60 ml.", wrong: ["น้ำเปล่า 30 ml."] } ] },
            { name: "ชาพีช 16oz. (หวานน้อย)", steps: [ { instruction: "ละลายชา", correct: "น้ำร้อน 3 oz.", wrong: ["น้ำร้อน 4 oz."] }, { instruction: "ปริมาณชาพีช", correct: "หวานน้อย ผงชาพีช 2 ช้อน", wrong: ["ผงชาพีช 3 ช้อน"] }, { instruction: "เติมน้ำ", correct: "น้ำเปล่า 60 ml.", wrong: ["น้ำเปล่า 30 ml."] } ] },

            // ชาไทย
            { name: "ชาไทย 16oz. (หวานปกติ)", steps: [ { instruction: "สกัดแรก", correct: "ผงชาตรามือ 3 ช้อน สกัด 1oz.", wrong: ["ผงชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพักชา"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 3oz. รวมเป็น 4oz.", wrong: ["รวมเป็น 5oz."] }, { instruction: "ความมัน", correct: "ครีมเทียม 1 ช้อน", wrong: ["ไม่ใส่ครีมเทียม"] }, { instruction: "ความหวานหลัก", correct: "นมข้น หวานปกติ 30ml.", wrong: ["นมข้น 20ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] } ] },
            { name: "ชาไทย 16oz. (หวานน้อย)", steps: [ { instruction: "สกัดแรก", correct: "ผงชาตรามือ 3 ช้อน สกัด 1oz.", wrong: ["ผงชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพักชา"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 3oz. รวมเป็น 4oz.", wrong: ["รวมเป็น 5oz."] }, { instruction: "ความมัน", correct: "ครีมเทียม 1 ช้อน", wrong: ["ไม่ใส่ครีมเทียม"] }, { instruction: "ความหวานหลัก", correct: "นมข้น หวานน้อย 20 ml.", wrong: ["นมข้น 10ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] } ] },
            { name: "ชาไทย 16oz. (หวาน 25%)", steps: [ { instruction: "สกัดแรก", correct: "ผงชาตรามือ 3 ช้อน สกัด 1oz.", wrong: ["ผงชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพักชา"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 3oz. รวมเป็น 4oz.", wrong: ["รวมเป็น 5oz."] }, { instruction: "ความมัน", correct: "ครีมเทียม 1 ช้อน", wrong: ["ไม่ใส่ครีมเทียม"] }, { instruction: "ความหวานหลัก", correct: "หวาน 25% นมข้น 10ml.", wrong: ["นมข้น 15ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] } ] },

            // ชาเขียว
            { name: "ชาเขียว 16oz. (หวานปกติ)", steps: [ { instruction: "สกัดแรก", correct: "ผงตรามือ 3 ช้อน สกัด 1oz.", wrong: ["ผงชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพักชา"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 3oz. รวมเป็น 4oz.", wrong: ["รวมเป็น 5oz."] }, { instruction: "ความหอม", correct: "ผงชาอโลม่า 1 ช้อนเล็ก", wrong: ["ไม่ใส่ผงชาอโลม่า"] }, { instruction: "ความมัน", correct: "ครีมเทียม 1 ช้อน", wrong: ["ไม่ใส่ครีมเทียม"] }, { instruction: "ความหวานหลัก", correct: "นมข้น หวานปกติ 30ml.", wrong: ["นมข้น 15ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] } ] },
            { name: "ชาเขียว 16oz. (หวานน้อย)", steps: [ { instruction: "สกัดแรก", correct: "ผงตรามือ 3 ช้อน สกัด 1oz.", wrong: ["ผงชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพักชา"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 3oz. รวมเป็น 4oz.", wrong: ["รวมเป็น 5oz."] }, { instruction: "ความหอม", correct: "ผงชาอโลม่า 1 ช้อนเล็ก", wrong: ["ไม่ใส่ผงชาอโลม่า"] }, { instruction: "ความมัน", correct: "ครีมเทียม 1 ช้อน", wrong: ["ไม่ใส่ครีมเทียม"] }, { instruction: "ความหวานหลัก", correct: "นมข้น หวานน้อย 15ml.", wrong: ["นมข้น 10ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] } ] },
            { name: "ชาเขียว 16oz. (หวาน 25%)", steps: [ { instruction: "สกัดแรก", correct: "ผงตรามือ 3 ช้อน สกัด 1oz.", wrong: ["ผงชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพักชา"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 3oz. รวมเป็น 4oz.", wrong: ["รวมเป็น 5oz."] }, { instruction: "ความหอม", correct: "ผงชาอโลม่า 1 ช้อนเล็ก", wrong: ["ไม่ใส่ผงชาอโลม่า"] }, { instruction: "ความมัน", correct: "ครีมเทียม 1 ช้อน", wrong: ["ไม่ใส่ครีมเทียม"] }, { instruction: "ความหวานหลัก", correct: "หวาน 25% นมข้น 10ml.", wrong: ["นมข้น 15ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] } ] },

            // นมชมพู
            { name: "นมชมพู 16oz. (หวานปกติ)", steps: [ { instruction: "นม", correct: "นมLay 150ml.", wrong: ["นมสด 120ml."] }, { instruction: "สีและความหวาน", correct: "น้ำแดง 40ml.", wrong: ["น้ำแดง 20ml."] } ] },
            { name: "นมชมพู 16oz. (หวาน 50%)", steps: [ { instruction: "นม", correct: "นมLay 150ml.", wrong: ["นมสด 120ml."] }, { instruction: "สีและความหวาน", correct: "หวาน 50% น้ำแดง 20 ml.", wrong: ["น้ำแดง 40ml."] } ] },

            // นมสดเย็น
            { name: "นมสดเย็น 16oz. (หวานปกติ)", steps: [ { instruction: "นม", correct: "นมLay 150ml.", wrong: ["นมสด 150ml."] }, { instruction: "ความหวาน", correct: "นมข้น หวานปกติ 30ml.", wrong: ["นมข้น 15ml."] } ] },
            { name: "นมสดเย็น 16oz. (หวานน้อย)", steps: [ { instruction: "นม", correct: "นมLay 150ml.", wrong: ["นมสด 150ml."] }, { instruction: "ความหวาน", correct: "หวานน้อย 15ml.", wrong: ["นมข้น 10ml."] } ] },
            { name: "นมสดเย็น 16oz. (หวาน 25%)", steps: [ { instruction: "นม", correct: "นมLay 150ml.", wrong: ["นมสด 150ml."] }, { instruction: "ความหวาน", correct: "หวาน 25% นมข้น 10 ml.", wrong: ["นมข้น 15ml."] } ] },

            // ชาเขียวมะนาว
            { name: "ชาเขียวมะนาว 16oz.", steps: [ { instruction: "สกัดแรก", correct: "ชาเขียว 3 ช้อน สกัด 1oz.", wrong: ["ชาเขียว 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพักชา"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 4oz. รวมเป็น 5oz.", wrong: ["รวมเป็น 4oz."] }, { instruction: "ความหวาน", correct: "ไซรัป 30ml.", wrong: ["ไซรัป 40ml."] }, { instruction: "ความเปรี้ยว", correct: "ผงมะนาว 1 ช้อนเล็ก (5 ml.)", wrong: ["ผงมะนาว 1 ½ ช้อน"] } ] },

            // เมนูอื่นๆ
            { name: "โกโก้ 16oz.", steps: [ { instruction: "ละลาย", correct: "น้ำร้อน 3oz.", wrong: ["น้ำร้อน 2oz."] }, { instruction: "ผงโกโก้", correct: "ผงโกโก้ 3oz.", wrong: ["ผงโกโก้ 2oz."] }, { instruction: "นม", correct: "นมLay 30ml.", wrong: ["นมสด 30ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 15ml.", wrong: ["ไซรัป 30ml."] }, { instruction: "ความหวานหลัก", correct: "นมข้น หวานปกติ 30ml.", wrong: ["นมข้น 15ml."] }, { instruction: "ตกแต่ง", correct: "ราดขอบแก้วซอสโกโก้ 2 รอบ", wrong: ["ไม่ต้องราด"] } ] },
            { name: "คาราเมลมัคคิอาโต 16oz.", steps: [ { instruction: "เบสกาแฟ", correct: "กาแฟ 2oz.", wrong: ["กาแฟ 50ml."] }, { instruction: "นม", correct: "นม 100 ml.", wrong: ["นม 120 ml."] }, { instruction: "ความหวาน", correct: "ไซรัปคาราเมล 30ml.", wrong: ["ไซรัปคาราเมล 15ml."] }, { instruction: "ตกแต่ง", correct: "ราดคาราเมลขอบแก้ว 2 รอบ", wrong: ["ไม่ต้องราด"] } ] },
            { name: "อเมริกาโน่น้ำช่อดอกมะพร้าว 16oz.", steps: [ { instruction: "เบสกาแฟ", correct: "กาแฟ 50ml.", wrong: ["กาแฟ 2oz."] }, { instruction: "ความหวาน", correct: "ช่อดอกน้ำมะพร้าว 90ml.", wrong: ["ช่อดอกน้ำมะพร้าว 120ml."] }, { instruction: "น้ำ", correct: "น้ำ 30ml.", wrong: ["ไม่ต้องเติมน้ำ"] }, { instruction: "ท็อปปิ้ง", correct: "ใส่เนื้อมะพร้าว 2 ชิ้น", wrong: ["ใส่ 1 ชิ้น"] } ] },
            
            { name: "อเมริกาโน่น้ำผึ้งมะนาว 16oz.", steps: [ { instruction: "ความหวาน 1", correct: "น้ำผึ้ง 15ml.", wrong: ["น้ำผึ้ง 30ml."] }, { instruction: "ความหวาน 2", correct: "ไซรัป 15ml.", wrong: ["ไซรัป 30ml."] }, { instruction: "ความเปรี้ยว", correct: "ผงมะนาว 1 ½ ช้อน", wrong: ["ผงมะนาว 1 ช้อน"] }, { instruction: "ละลาย", correct: "ใส่น้ำร้อนให้ถึง 4oz.", wrong: ["ใส่น้ำร้อน 5oz."] }, { instruction: "กาแฟ", correct: "กาแฟ 50ml. (แยกชั้น)", wrong: ["กาแฟ 2oz."] } ] },
            { name: "อเมริกาโน่ส้ม 16oz.", steps: [ { instruction: "เบสกาแฟ", correct: "กาแฟ 50ml.", wrong: ["กาแฟ 2oz."] }, { instruction: "น้ำผลไม้", correct: "น้ำส้ม 1 ขวด (แยกชั้น)", wrong: ["น้ำส้ม 90ml."] } ] },
            
            { name: "ชามะนาว 16oz.", steps: [ { instruction: "สกัดแรก", correct: "ผงชาตรามือผสมมังกร 3 ช้อน สกัด 1oz.", wrong: ["ผงชาตรามือ 3 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพัก"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 4oz. รวมเป็น 5oz.", wrong: ["รวมเป็น 4oz."] }, { instruction: "ความหวาน", correct: "ไซรัป 30ml.", wrong: ["น้ำผึ้ง 30ml."] }, { instruction: "ความเปรี้ยว", correct: "ผงมะนาว 1 ½ ช้อนเล็ก", wrong: ["ผงมะนาว 1 ช้อน"] } ] },
            
            { name: "โกโก้มินท์ 16oz. (แยกชั้น)", steps: [ { instruction: "ละลายโกโก้", correct: "น้ำร้อน 2oz.", wrong: ["น้ำร้อน 3oz."] }, { instruction: "ปริมาณผง", correct: "ผงโกโก้ 2oz.", wrong: ["ผงโกโก้ 3oz."] }, { instruction: "นม", correct: "นมสด 100ml.", wrong: ["นมLay 120ml."] }, { instruction: "ความหวาน", correct: "ไซรัปมินท์ 30ml.", wrong: ["ไซรัปมินท์ 15ml."] }, { instruction: "ตกแต่ง", correct: "ราดขอบแก้วซอสโกโก้ 2 รอบ", wrong: ["ไม่ต้องราด"] } ] },
            
            { name: "ชาเขียวน้ำผึ้งมะนาว 16oz.", steps: [ { instruction: "สกัดแรก", correct: "ผงชาตรามือ 3 ช้อน สกัด 1oz.", wrong: ["ชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพัก"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 4oz. รวมเป็น 5oz.", wrong: ["รวมเป็น 4oz."] }, { instruction: "ความหวาน 1", correct: "ไซรัป 15ml.", wrong: ["ไซรัป 30ml."] }, { instruction: "ความหวาน 2", correct: "น้ำผึ้ง 15ml.", wrong: ["น้ำผึ้ง 30ml."] }, { instruction: "ความเปรี้ยว", correct: "ผงมะนาว 1 ½ ช้อนเล็ก", wrong: ["ผงมะนาว 5 ml."] } ] },
            
            { name: "ชากุหลาบ 16oz.", steps: [ { instruction: "สกัดแรก", correct: "ผงชากุหลาบ 3 ช้อน สกัด 1oz.", wrong: ["ชา 2 ช้อน สกัด 1oz."] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพัก"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 3oz. รวมเป็น 4oz.", wrong: ["รวมเป็น 5oz."] }, { instruction: "ความมัน", correct: "ครีมเทียม 1 ช้อน", wrong: ["ไม่ใส่ครีมเทียม"] }, { instruction: "ความหวานหลัก", correct: "นมข้น 30ml.", wrong: ["นมข้น 15ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] } ] },
            
            { name: "เมนูโซดา 16oz. (เช่น บลูฮาวาย)", steps: [ { instruction: "ไซรัป", correct: "ไซรัปผลไม้ 40ml.", wrong: ["ไซรัปผลไม้ 30ml."] }, { instruction: "โซดาแรก", correct: "ใส่โซดา 30ml. คนให้เข้ากัน", wrong: ["ใส่โซดาทีเดียวเต็ม"] }, { instruction: "ความเปรี้ยว", correct: "เฉพาะบลูฮาวายใส่ผงมะนาว 1/2 ช้อน", wrong: ["ใส่ 1 ช้อน"] }, { instruction: "น้ำแข็ง", correct: "ใส่น้ำแข็ง", wrong: ["ใส่น้ำเปล่า"] }, { instruction: "โซดาสุดท้าย", correct: "ใส่โซดาให้เต็ม", wrong: ["ใส่น้ำเปล่าให้เต็ม"] } ] },
            
            { name: "นมสดคาราเมล 16oz.", steps: [ { instruction: "นม", correct: "นมสด 150ml.", wrong: ["นมLay 150ml."] }, { instruction: "ความหวาน", correct: "ไซรัปคาราเมล 30ml.", wrong: ["ไซรัป 15ml."] }, { instruction: "ตกแต่ง", correct: "ราดคาราเมลขอบแก้ว 2 รอบ", wrong: ["ไม่ต้องราด"] } ] },
            
            { name: "เพียวมัทฉะ (เขียนมือ)", steps: [ { instruction: "มัทฉะ", correct: "ผงมัทฉะ 3 g.", wrong: ["ผงมัทฉะ 5 g."] }, { instruction: "ละลาย", correct: "น้ำร้อน 2 oz.", wrong: ["น้ำร้อน 3 oz."] }, { instruction: "น้ำ", correct: "เติมน้ำเปล่าในแก้ว 100 ml.", wrong: ["น้ำเปล่า 150 ml."] }, { instruction: "ขั้นตอนสุดท้าย", correct: "เอามัทฉะราดข้างบน", wrong: ["คนให้เข้ากัน"] } ] },
            
            { name: "ลิ้นจี่น้ำแดง 16oz.", steps: [ { instruction: "ลิ้นจี่", correct: "ไซรัปลิ้นจี่ 1 ขวด", wrong: ["ไซรัปลิ้นจี่ 30ml."] }, { instruction: "น้ำแดง", correct: "น้ำแดง 20 ml.", wrong: ["น้ำแดง 40 ml."] } ] },
            { name: "ชาพีช + น้ำผึ้ง 16oz.", steps: [ { instruction: "ความหวาน", correct: "น้ำผึ้ง 30 ml.", wrong: ["น้ำผึ้ง 15 ml."] }, { instruction: "ละลาย", correct: "น้ำร้อน 3 oz.", wrong: ["น้ำร้อน 4 oz."] }, { instruction: "ชาพีช", correct: "ชาพีช 2 ช้อน", wrong: ["ชาพีช 3 ช้อน"] }, { instruction: "น้ำ", correct: "น้ำเปล่า 60 ml.", wrong: ["น้ำเปล่า 30 ml."] } ] },
            
            // โคลด์โฟม
            { name: "โคลด์โฟมมัทฉะช่อน้ำดอกมะพร้าว", steps: [ { instruction: "โฟม: ส่วนของนม", correct: "นมสด 60ml.", wrong: ["นมสด 90ml."] }, { instruction: "โฟม: วิปครีม", correct: "วิป 30ml.", wrong: ["ไม่ใส่วิป"] }, { instruction: "โฟม: ส่วนของชา", correct: "ผงมัทฉะ 5-6g. (ตีจนฟองหนืด)", wrong: ["มัทฉะ 3g."] }, { instruction: "เบส", correct: "ช่อดอกน้ำมะพร้าว 90ml.", wrong: ["ช่อดอก 120ml."] }, { instruction: "น้ำ", correct: "น้ำ 30ml.", wrong: ["ไม่ต้องเติมน้ำ"] }, { instruction: "ท็อปปิ้ง", correct: "ใส่เนื้อมะพร้าว 2 ชิ้น", wrong: ["ใส่ 1 ชิ้น"] } ] },
            { name: "โคลด์โฟม ชาเขียวช่อน้ำดอกมะพร้าว", steps: [ { instruction: "โฟม: ส่วนของนม", correct: "นมสด 60ml.", wrong: ["นมสด 90ml."] }, { instruction: "โฟม: วิปครีม", correct: "วิป 30ml.", wrong: ["ไม่ใส่วิป"] }, { instruction: "โฟม: ส่วนของชา", correct: "ชาเขียว 1oz.(30ml.)", wrong: ["ผงชาเขียว 5g."] }, { instruction: "เบส", correct: "ช่อดอกน้ำมะพร้าว 90ml.", wrong: ["ช่อดอก 120ml."] }, { instruction: "น้ำ", correct: "น้ำ 30ml.", wrong: ["ไม่ต้องเติมน้ำ"] } ] },
            { name: "โคลด์โฟมกาแฟลาเต้ช่อน้ำดอกมะพร้าว", steps: [ { instruction: "โฟม: ส่วนของนม", correct: "นมสด 60ml.", wrong: ["นมสด 90ml."] }, { instruction: "โฟม: วิปครีม", correct: "วิป 30ml.", wrong: ["ไม่ใส่วิป"] }, { instruction: "โฟม: กาแฟ", correct: "กาแฟ 30ml. (ตีจนฟองหนืด)", wrong: ["กาแฟ 50ml."] }, { instruction: "เบส", correct: "ช่อดอกน้ำมะพร้าว 90ml.", wrong: ["ช่อดอก 120ml."] }, { instruction: "น้ำ", correct: "น้ำ 30ml.", wrong: ["ไม่ต้องเติมน้ำ"] } ] },
            { name: "โคลด์โฟม ชาไทยช่อน้ำดอกมะพร้าว", steps: [ { instruction: "โฟม: ส่วนของนม", correct: "นมสด 60ml.", wrong: ["นมสด 90ml."] }, { instruction: "โฟม: วิปครีม", correct: "วิป 30ml.", wrong: ["ไม่ใส่วิป"] }, { instruction: "โฟม: ส่วนของชา", correct: "ชาไทย 1oz.(30ml.)", wrong: ["ผงชา 5g."] }, { instruction: "เบส", correct: "ช่อดอกน้ำมะพร้าว 90ml.", wrong: ["ช่อดอก 120ml."] }, { instruction: "น้ำ", correct: "น้ำ 30ml.", wrong: ["ไม่ต้องเติมน้ำ"] } ] },
            { name: "โคลด์โฟม โกโก้ช่อน้ำดอกมะพร้าว", steps: [ { instruction: "โฟม: ส่วนของนม", correct: "นมสด 60ml.", wrong: ["นมสด 90ml."] }, { instruction: "โฟม: วิปครีม", correct: "วิป 30ml.", wrong: ["ไม่ใส่วิป"] }, { instruction: "โฟม: โกโก้", correct: "โกโก้ 1 ช้อน (ตีจนฟองหนืด)", wrong: ["น้ำโกโก้ 30ml."] }, { instruction: "เบส", correct: "ช่อดอกน้ำมะพร้าว 90ml.", wrong: ["ช่อดอก 120ml."] }, { instruction: "น้ำ", correct: "น้ำ 30ml.", wrong: ["ไม่ต้องเติมน้ำ"] } ] },
            
            // มัทฉะแบบต่างๆ
            { name: "ชาใสกุหลาบ 16oz.", steps: [ { instruction: "สกัดแรก", correct: "ผงชากุหลาบ สกัด 1oz.", wrong: ["ผงชากุหลาบ 2 ช้อน"] }, { instruction: "จังหวะชง", correct: "พักชา 10 วินาที", wrong: ["ไม่ต้องพัก"] }, { instruction: "สกัดน้ำเพิ่ม", correct: "กดปุ่มน้ำเพิ่มอีก 4oz. รวมเป็น 5oz.", wrong: ["รวมเป็น 4oz."] }, { instruction: "ความหวาน", correct: "ไซรัป 30ml.", wrong: ["ไซรัป 15ml."] } ] },
            { name: "เพียวมัทฉะ (สูตรพิมพ์)", steps: [ { instruction: "น้ำ", correct: "น้ำเปล่า 150ml.", wrong: ["น้ำร้อน 150ml."] }, { instruction: "มัทฉะ", correct: "มัทฉะ 1 ช้อน", wrong: ["มัทฉะ 3g."] }, { instruction: "ขั้นตอน", correct: "ตีให้เข้ากัน", wrong: ["ราดข้างบน"] } ] },
            { name: "มัทฉะลาเต้ 16oz.", steps: [ { instruction: "มัทฉะ", correct: "ผงมัทฉะ 1 ช้อน", wrong: ["ผงมัทฉะ 3g."] }, { instruction: "ละลายชา", correct: "น้ำร้อน 2oz.", wrong: ["น้ำร้อน 3oz."] }, { instruction: "นม", correct: "นม 100ml.", wrong: ["นม 120ml."] }, { instruction: "ความหวานหลัก", correct: "นมข้น 30ml.", wrong: ["นมข้น 15ml."] }, { instruction: "ความหวานเสริม", correct: "ไซรัป 5ml.", wrong: ["ไม่ใส่ไซรัป"] } ] },
            { name: "มัทฉะน้ำช่อดอกมะพร้าว (แยกชั้น)", steps: [ { instruction: "มัทฉะ", correct: "ผงมัทฉะ 1 ช้อน", wrong: ["ผงมัทฉะ 3g."] }, { instruction: "ละลายชา", correct: "น้ำร้อน 2oz.", wrong: ["น้ำร้อน 3oz."] }, { instruction: "เบส", correct: "ช่อดอกน้ำมะพร้าว 90ml.", wrong: ["ช่อดอก 120ml."] }, { instruction: "น้ำ", correct: "น้ำ 30ml.", wrong: ["ไม่ต้องเติมน้ำ"] }, { instruction: "ท็อปปิ้ง", correct: "ใส่เนื้อมะพร้าว 2 ชิ้น", wrong: ["ใส่ 1 ชิ้น"] } ] },
            { name: "มัทฉะน้ำส้ม (แยกชั้น)", steps: [ { instruction: "มัทฉะ", correct: "ผงมัทฉะ 1 ช้อน", wrong: ["ผงมัทฉะ 3g."] }, { instruction: "ละลายชา", correct: "น้ำร้อน 2oz.", wrong: ["น้ำร้อน 3oz."] }, { instruction: "น้ำผลไม้", correct: "น้ำส้ม 1 ขวด 120ml.", wrong: ["น้ำส้ม 90ml."] } ] },
            { name: "มัทฉะมะนาว (แยกชั้น)", steps: [ { instruction: "มัทฉะ", correct: "ผงมัทฉะ 1 ช้อน", wrong: ["ผงมัทฉะ 3g."] }, { instruction: "ละลายชา", correct: "น้ำร้อน 2oz.", wrong: ["น้ำร้อน 3oz."] }, { instruction: "ความหวาน", correct: "ไซรัป 30 ml.", wrong: ["ไซรัป 15ml."] }, { instruction: "ความเปรี้ยว", correct: "ผงมะนาว 1 ½ ช้อน", wrong: ["ผงมะนาว 1 ช้อน"] }, { instruction: "ละลายน้ำ", correct: "ใส่น้ำร้อนให้ถึง 4oz.", wrong: ["ใส่น้ำร้อน 5oz."] } ] },
            { name: "มัทฉะน้ำผึ้งมะนาว (แยกชั้น)", steps: [ { instruction: "มัทฉะ", correct: "ผงมัทฉะ 1 ช้อน", wrong: ["ผงมัทฉะ 3g."] }, { instruction: "ละลายชา", correct: "น้ำร้อน 2oz.", wrong: ["น้ำร้อน 3oz."] }, { instruction: "ความหวาน 1", correct: "น้ำผึ้ง 15ml.", wrong: ["น้ำผึ้ง 30ml."] }, { instruction: "ความหวาน 2", correct: "ไซรัป 15ml.", wrong: ["ไซรัป 30ml."] }, { instruction: "ความเปรี้ยว", correct: "ผงมะนาว 1 ½ ช้อน", wrong: ["ผงมะนาว 1 ช้อน"] }, { instruction: "ละลายน้ำ", correct: "ใส่น้ำร้อนให้ถึง 4oz.", wrong: ["ใส่น้ำร้อน 5oz."] } ] }
        ];
